const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;
for(const p of ['js/core.js','js/physics.js','js/input.js','js/character.js','js/characters/rubania.js','js/bosses/slime.js','js/stages/outer-wall.js','js/stages/wine-cellar.js'])vm.runInThisContext(fs.readFileSync(p,'utf8'));
const world={width:1920,floorY:660,objects:Game.Stages.wineCellar.objects.map(o=>({...o})),solids:[{x:0,y:660,w:1920,h:60}]};
const b=new Game.CellarEncounter(world),f=new Game.Fighter(Game.Characters.rubania,{x:340,y:490});
b.spillWine(420,210);assert.equal(world.wineLeaks.length,1);assert(world.objects[0].leaking);
b.spillWine(420,210);assert.equal(world.wineLeaks.length,1,'same barrel does not spawn duplicate streams');
b.spillWine(20,20);assert.equal(world.wineLeaks.length,1,'shots far from barrels do not spill');
for(let i=0;i<60;i++)b.update(f);const leak=world.wineLeaks[0];assert.equal(leak.bottom,660);
assert.equal(Game.cellarWineSlow(world,{x:410,y:300,w:40,h:80}),0.55,'falling stream slows');
assert.equal(Game.cellarWineSlow(world,{x:350,y:490,w:40,h:170}),0.55,'puddle slows');
assert.equal(Game.cellarWineSlow(world,{x:200,y:490,w:40,h:170}),1,'dry ground is unaffected');
assert.equal(Game.cellarWineSlow(world,{x:350,y:350,w:40,h:100}),1,'jumping above puddle avoids it');
b.world.timeStopped=true;const age=leak.age;b.update(f);assert.equal(leak.age,age);b.world.timeStopped=false;
const input=new Game.Input();input.axisX=()=>1;f.x=350;f.grounded=true;f.update(input,world);assert.equal(f.vx,f.def.stats.walkSpd*0.55);
f.x=100;f.update(input,world);assert.equal(f.vx,f.def.stats.walkSpd);
b.animations={gunready:{}};b.phase='fastlock';b.phaseTick=7;b.lockedTarget={x:900,y:120,w:110,h:180};b.update(f);assert.equal(world.wineLeaks.length,2,'actual fast shot spills nearest barrel');
let rectangles=[];const ctx={save(){},restore(){},fillRect(...args){rectangles.push(args);}};
Game.drawCellarWine(ctx,world,0,'stream');assert(rectangles.some(rect=>rect[1]<600));assert(rectangles.every(rect=>rect[2]<=32),'stream pass excludes wide puddles');
rectangles=[];Game.drawCellarWine(ctx,world,0,'puddle');assert(rectangles.length>0);assert(rectangles.every(rect=>rect[1]>=648),'puddle pass excludes falling streams');
console.log('PASS: separate stream/puddle passes, closest barrel, actual fast shot, slowdown and clock freeze.');
