const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;
for(const p of ['js/core.js','js/physics.js','js/character.js','js/characters/rubania.js','js/bosses/slime.js','js/stages/outer-wall.js','js/stages/wine-cellar.js'])vm.runInThisContext(fs.readFileSync(p,'utf8'));
function setup(crouching=false){
  const world={width:1280,floorY:660,timeStopped:false,enemyDamageMultiplier:1};
  const encounter=new Game.CellarEncounter(world);encounter.animations={aim:[{},{},{},{}],recoil:[{},{},{},{}]};
  const fighter=new Game.Fighter(Game.Characters.rubania,{x:500,y:crouching?575:490});
  if(crouching)fighter.h=85;
  return {world,encounter,fighter};
}
const standing=setup(),initialHp=standing.fighter.hp;
for(let i=0;i<109;i++)standing.encounter.update(standing.fighter);
assert.equal(standing.encounter.phase,'aim');assert.equal(standing.fighter.hp,initialHp);
standing.encounter.update(standing.fighter);assert.equal(standing.encounter.phase,'oneshoot');
assert.equal(Math.abs(standing.encounter.bullets[0].vx),40);
assert(40>Game.Characters.rubania.stats.knifeSpeed);
for(let i=0;i<12;i++)standing.encounter.update(standing.fighter);
assert.equal(standing.fighter.hp,initialHp-18);
const ducking=setup(true);
for(let i=0;i<150;i++)ducking.encounter.update(ducking.fighter);
assert.equal(ducking.fighter.hp,initialHp,'crouching avoids the horizontal bullet');
const stopped=setup();stopped.world.timeStopped=true;
stopped.encounter.bullets.push({x:900,y:527,w:16,h:6,vx:-40,damage:18});
stopped.encounter.update(stopped.fighter);
assert.equal(stopped.encounter.cooldown,90);assert.equal(stopped.encounter.bullets[0].x,900);
const zero=setup();zero.fighter.allowZeroHp=true;zero.fighter.hp=1;
zero.fighter.takeHit({x:800,y:527,w:16,h:6,damage:18});assert.equal(zero.fighter.hp,0);
zero.fighter.invuln=0;zero.fighter.hitT=0;
zero.fighter.takeHit({x:800,y:527,w:16,h:6,damage:18});assert(zero.fighter.hitT>0,'zero HP retains hit reactions');
const burst=setup(true);burst.encounter.attackCount=1;let shots=0;const shotTimes=[];
const fire=burst.encounter.fireBullet;
burst.encounter.fireBullet=function(){shots++;shotTimes.push({phase:this.phase,tick:this.phaseTick,worldTick:this.tick});fire.call(this);};
for(let i=0;i<210;i++)burst.encounter.update(burst.fighter);
assert.equal(shots,6,'one initial shot plus five rapid shots');assert.equal(burst.encounter.phase,'idle');
assert.equal(burst.fighter.hp,initialHp,'crouching also avoids the full burst');
assert.deepEqual(shotTimes.map(s=>[s.phase,s.tick]),[['oneshoot',0],['panning',0],['panning',8],['panning',16],['panning',24],['panning',32]],'exactly one bullet at each panning cycle start');
assert.equal(shotTimes[0].worldTick,110,'aim finishes in 20 ticks after the 90-tick cooldown');
assert.equal(shotTimes[1].worldTick-shotTimes[0].worldTick,32,'oneshoot uses its original playback speed');
const frozenBurst=setup(true);frozenBurst.encounter.phase='panning';frozenBurst.encounter.phaseTick=7;
let frozenShots=0;frozenBurst.encounter.fireBullet=()=>frozenShots++;
frozenBurst.world.timeStopped=true;frozenBurst.encounter.update(frozenBurst.fighter);
assert.equal(frozenBurst.encounter.phaseTick,7);assert.equal(frozenShots,0);
frozenBurst.world.timeStopped=false;frozenBurst.encounter.update(frozenBurst.fighter);
assert.equal(frozenShots,1,'resuming at the loop boundary emits only one bullet');
console.log('PASS: shot timing, fast swept bullets, crouch evasion, time stop and zero-HP hit reactions.');
