const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;
const nodes=new Map();function node(id){if(!nodes.has(id)){const classes=new Set();nodes.set(id,{events:{},style:{},classList:{add:c=>classes.add(c),remove:c=>classes.delete(c),toggle(c,on){on?classes.add(c):classes.delete(c)},contains:c=>classes.has(c)},addEventListener(k,f){(this.events[k]||=[]).push(f)},setPointerCapture(){},getBoundingClientRect:()=>({left:0,top:0,width:200,height:200})});}return nodes.get(id);}
global.document={getElementById:node,querySelector:()=>node('screen'),addEventListener(){}};
node('screen').style.setProperty=function(key,value){this[key]=value};
global.addEventListener=()=>{};const media={matches:true};global.matchMedia=()=>media;
const storage=new Map([['rubania-mobile-reversed','true']]);global.localStorage={getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)};
let refresh;global.requestAnimationFrame=f=>refresh=f;
for(const file of ['js/input.js','js/mobile.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'));
const input=new Game.Input(),fighter={def:{stats:{tapWindow:15}},canStartRun:()=>false};
assert(!node('screen').classList.contains('mobile-reversed'),'old reversed preference resets to standard default');
Game.menu={active:false};Game.bindMobileInput(input,fighter);
function send(id,type,pointerId,x=100,y=100){for(const f of node(id).events[type]||[])f({pointerId,clientX:x,clientY:y,preventDefault(){}});}
send('mobile-stick','pointerdown',1,170,100);assert(input.right);
send('mobile-jump','pointerdown',2);assert(input.jump&&input.jumpPressed&&input.right,'simultaneous movement and jump');
send('mobile-attack','pointerdown',3);assert(input.attack&&input.attackPressed&&input.jump);
send('mobile-jump','pointercancel',2);assert(!input.jump&&input.attack&&input.right);
send('mobile-stick','pointermove',1,140,160);assert(input.down&&input.right,'diagonal stick');
send('mobile-stick','pointerup',1);assert(!input.right&&!input.down);
send('mobile-subweapon','pointerdown',4);assert(input.subweaponPressed);
send('mobile-dodge','pointerdown',5);assert(input.backstepPressed);
assert(node('mobile-dodge').classList.contains('pressed'));send('mobile-dodge','pointerup',5);assert(!node('mobile-dodge').classList.contains('pressed'));
node('game').width=1280;assert.equal(Game.mobileHudScale(),6.4,'existing canvas HUD scales to display width');
node('reverse-mobile-controls').checked=true;send('reverse-mobile-controls','change',0);
assert(node('screen').classList.contains('mobile-reversed'));assert.equal(storage.get('rubania-mobile-reversed-v2'),'true');assert(!input.attack);
Game.shop={active:true};refresh();assert(node('mobile-controls').hidden);input.clearEdges();send('mobile-jump','pointerdown',6);assert(!input.jumpPressed);
Game.shop.active=false;refresh();assert(!node('mobile-controls').hidden);
media.matches=false;refresh();assert(node('mobile-controls').hidden);
assert.equal(Game.drawMobileTimer({timer:{}},'00:12'),false,'desktop timer stays inside game');
media.matches=true;global.innerWidth=800;global.innerHeight=390;global.screen={orientation:{angle:90}};
send('mobile-stick','pointerdown',10,100,30);assert(input.right&&!input.down,'rotated joystick respects portrait directions');send('mobile-stick','pointerup',10);
Game.drawMobileTimer({timer:{expired:false},timeStopped:true},'01:12');
assert.equal(node('mobile-timer-value').textContent,'01:12');assert.equal(node('mobile-timer-label').textContent,'시간 정지');
setImmediate(async()=>{
  let attempts=0,fullscreens=0;
  global.screen.orientation.lock=async value=>{assert.equal(value,'portrait-primary');if(++attempts===1)throw Error('fullscreen required');};
  node('screen').requestFullscreen=async()=>{fullscreens++;document.fullscreenElement=node('screen')};
  await Game.lockMobilePortrait();assert.equal(attempts,2);assert.equal(fullscreens,1);
  document.fullscreenElement=null;await Game.restoreMobileFullscreen();assert.equal(fullscreens,2,'resume requests fullscreen even if locking can succeed separately');
  global.screen.orientation.lock=async()=>{throw Error('not supported')};
  await Game.lockMobilePortrait();
  console.log('PASS: portrait lock fullscreen retry, safe rejection, rotated input and relocated timer.');
});
console.log('PASS: touch multitouch, diagonals, cancellation, mirrored saved layout, overlay and desktop blocking.');
const pulses=[];
window.navigator.vibrate=duration=>pulses.push(duration);
send('mobile-attack','pointerdown',11);send('mobile-attack','pointerup',11);
send('mobile-stick','pointerdown',12,100,30);send('mobile-stick','pointermove',12,170,100);send('mobile-stick','pointerup',12);
assert.deepEqual(pulses,[],'buttons and joystick no longer request vibration');
delete window.navigator.vibrate;
