const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;
for(const file of ['js/core.js','js/physics.js','js/input.js','js/character.js','js/characters/rubania.js','js/bosses/slime.js','js/stages/outer-wall.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'));
const platform=Game.createOuterWallPlatform();
const world={width:1280,height:720,floorY:660,ceilingY:20,solids:[{x:0,y:660,w:1280,h:60},platform]};
const fighter=new Game.Fighter(Game.Characters.rubania,{x:600,y:550-Game.Characters.rubania.stats.standH});
fighter.vy=0;
Game.updateOuterWallPlatforms(world,fighter,[]);assert.equal(platform.state,'warning');
let positive=false,negative=false;
for(let i=0;i<90;i++){Game.updateOuterWallPlatforms(world,fighter,[]);positive ||= platform.angle>0;negative ||= platform.angle<0;}
assert(positive&&negative);assert(platform.disabled);assert.equal(platform.state,'falling');
fighter.vy=1;Game.moveAndCollide(fighter,world.solids,world);assert(fighter.y+fighter.h>550,'falling platform releases player');
while(platform.state==='falling')Game.updateOuterWallPlatforms(world,fighter,[]);
assert.equal(platform.state,'waiting');
world.timeStopped=true;Game.updateOuterWallPlatforms(world,fighter,[]);assert.equal(platform.ticks,120);world.timeStopped=false;
for(let i=0;i<120;i++)Game.updateOuterWallPlatforms(world,fighter,[]);
assert.equal(platform.state,'rising');assert(platform.disabled);
while(platform.state==='rising')Game.updateOuterWallPlatforms(world,fighter,[]);
assert.equal(platform.y,550);assert(!platform.disabled);
const encounter=new Game.SlimeEncounter(world),slime=encounter.slimes[0];encounter.pressCooldown=999;
slime.cx=640;slime.feet=549;slime.vy=2;slime.bouncing=false;encounter.sync(slime);
fighter.x=600;fighter.y=0;encounter.update(fighter);
assert.equal(slime.feet,550);assert.equal(slime.vy,0);
Game.updateOuterWallPlatforms(world,fighter,[slime]);assert.equal(platform.state,'warning','slime triggers collapse too');
slime.feet=560;slime.vy=-5;assert.equal(encounter.landingSurface(slime,565),660,'ascending slime passes through underside');
platform.disabled=true;slime.feet=551;slime.vy=2;assert.equal(encounter.landingSurface(slime,549),660);
Object.assign(platform,Game.createOuterWallPlatform());
fighter.y=550-fighter.h;fighter.grounded=true;fighter.vy=0;
const input=new Game.Input();input.down=true;input.jumpPressed=true;
fighter.update(input,{...world,enemies:[]});
assert.equal(fighter.slideT,0);assert(!fighter.grounded);assert(fighter.y+fighter.h>550);
const floorFighter=new Game.Fighter(Game.Characters.rubania,{x:600,y:660-Game.Characters.rubania.stats.standH});
floorFighter.grounded=true;floorFighter.crouching=true;floorFighter.setHeight(floorFighter.def.stats.crouchH);
const floorInput=new Game.Input();floorInput.down=true;floorInput.jumpPressed=true;
floorFighter.update(floorInput,{...world,enemies:[]});assert(floorFighter.slideT>0,'floor sliding retained');
slime.cx=640;slime.feet=549;slime.vy=5;slime.vx=0;slime.press='flight';slime.pressTarget=640;
encounter.updatePress(slime);
assert(platform.disabled);assert.equal(platform.state,'falling');assert(slime.feet>550);assert.equal(slime.press,'flight');
while(slime.press==='flight')encounter.updatePress(slime);
assert.equal(slime.feet,660,'body press continues to floor');
console.log('PASS: shared platform warning, fall, regeneration, time stop and slime landing.');
