const fs=require('fs'),vm=require('vm'),assert=require('assert');
global.window=global;
for(const file of ['js/core.js','js/character.js','js/characters/rubania.js','js/bosses/slime.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'));
const world={width:1280,height:720,floorY:660,ceilingY:20,solids:[],enemies:[]};
const f=new Game.Fighter(Game.Characters.rubania,{x:80,y:490});
f.ownedSubweapons.add('clock');f.ownedSubweapons.add('cross');
const input={clockPressed:true,subweaponPressed:true};
f.mp=19.99;f.updateSubweapon(input,world);assert(!f.clockActive);
f.mp=20;f.updateSubweapon(input,world);assert(f.clockActive);assert(world.timeStopped);assert.equal(f.clockPulse,36);
const e=new Game.SlimeEncounter(world);world.enemies=e.slimes;
const slime=e.slimes[0];slime.vx=5;slime.vy=-3;slime.bouncing=true;
const wave={x:100,y:600,w:64,h:28,vx:6,life:90};e.waves=[wave];
const snapshot=JSON.stringify({cx:slime.cx,feet:slime.feet,idle:slime.idleTick,vx:slime.vx,vy:slime.vy,cooldown:e.pressCooldown,wave});
e.update(f);assert.equal(JSON.stringify({cx:slime.cx,feet:slime.feet,idle:slime.idleTick,vx:slime.vx,vy:slime.vy,cooldown:e.pressCooldown,wave}),snapshot);
const hp=slime.hp;slime.takeDamage(20,f);assert.equal(slime.hp,hp-20);assert.equal(slime.vx,5);
input.clockPressed=false;input.subweaponPressed=true;input.crossPressed=true;
const start=f.mp;
for(let i=0;i<5;i++)f.updateSubweapon(input,world);
assert.equal(f.mp,start);
f.updateSubweapon(input,world);assert.equal(f.mp,start-1);assert(f.clockActive);assert.equal(f.crosses.length,0);
input.crossPressed=false;
while(f.clockActive)f.updateSubweapon(input,world);
assert.equal(f.mp,0);assert(!world.timeStopped);
e.update(f);assert.notEqual(slime.cx,1280*.76);assert.equal(wave.life,89);
world.timeStopped=true;e.def.timeStopImmune=true;const cx=slime.cx;e.update(f);assert.notEqual(slime.cx,cx);e.def.timeStopImmune=false;
console.log('PASS: minimum MP, uncancellable drain, no regen/other subweapon, frozen motion/timers/waves, damage during stop, resume and boss immunity.');
