const fs=require('fs'),vm=require('vm'),assert=require('assert');
global.window=global;
for(const file of ['js/core.js','js/bosses/slime.js'])vm.runInThisContext(fs.readFileSync(file,'utf8'));
const world={width:1280,height:720,timer:Game.createStageTimer(120),enemyDamageMultiplier:1};
Game.updateStageTimer(world,false);assert.equal(world.timer.remainingFrames,7200);
world.timeStopped=true;for(let i=0;i<600;i++)Game.updateStageTimer(world,true);
assert.equal(world.timer.remainingFrames,7200);
world.timeStopped=false;for(let i=0;i<7199;i++)Game.updateStageTimer(world,true);
assert(!world.timer.expired);assert.equal(world.enemyDamageMultiplier,1);
Game.updateStageTimer(world,true);assert(world.timer.expired);assert.equal(world.enemyDamageMultiplier,2);
Game.updateStageTimer(world,true);assert.equal(world.timer.remainingFrames,0);
const e=new Game.SlimeEncounter(world),s=e.slimes[0];let damage=[];
const f={hp:100,kickInvuln:0,hurtBox:()=>s.attack,takeHit:h=>damage.push(h.damage)};
e.resolveContact(f);assert(damage.includes(36));
damage=[];s.ceilingState='fall';e.resolveContact(f);assert(damage.includes(48));
damage=[];s.ceilingState=null;s.press='flight';s.vy=1;e.resolveContact(f);assert(damage.includes(56));
damage=[];e.waves=[Object.assign({},s.attack,{damage:16,hit:false})];e.resolveContact(f);assert(damage.includes(32));
assert.equal(f.hp,100);
console.log('PASS: 120 seconds, inactive/time-stop pause, expiry without game over, 2x body/drop/press/wave damage.');
