const fs=require('fs'),vm=require('vm'),assert=require('assert');global.window=global;
for(const p of ['js/core.js','js/physics.js','js/input.js','js/character.js','js/characters/rubania.js','js/bosses/slime.js','js/stages/outer-wall.js','js/stages/wine-cellar.js','js/hud.js','js/shop-system.js'])vm.runInThisContext(fs.readFileSync(p,'utf8'));
assert.equal(Game.cellarBossLabel({}),'성주의 재물로 움직이는 자');
assert.equal(Game.cellarBossLabel({knowsCellarBoss:true}),'미츄헨 데슈타프');
Game.Input.prototype.bind=function(){};
let actor;Game.Fighter.prototype.load=function(){actor=this;return Promise.resolve();};
Game.loadImage=src=>Promise.resolve(src.endsWith('/holster.png')?{width:1848,height:229}:{width:src.includes('stage2')?3216:768,height:src.includes('stage2')?201:438});
const translations=[];const draws=[];const ctx=new Proxy({}, {get:(_,key)=>key==='drawImage'?(...a)=>draws.push(a):key==='translate'?(...a)=>translations.push(a):()=>{},set:()=>true});
const handlers=new Map();const els=new Map();global.document={createElement(){return {getContext:()=>ctx};},getElementById(id){if(!els.has(id))els.set(id,{getContext:()=>ctx,addEventListener(type,fn){handlers.set(id+type,fn);},focus(){}});return els.get(id);}};
Game.shop={active:false,drawPortrait(){}};let loop;global.requestAnimationFrame=fn=>loop=fn;
vm.runInThisContext(fs.readFileSync('js/game.js','utf8'));
setImmediate(()=>{
 assert.equal(actor.x,80,'stage one retains its original player position');
 actor.hp=67;actor.knowsCellarBoss=true;actor.lives=2;actor.ownedSubweapons.add('cross');
 Game.shop.checkpoint=Game.captureShopCheckpoint(actor,2500,[]);Game.shop.open=function(points,actor,restoring){this.active=true;this.restored={points,restoring};};Game.clearSequence={};Game.shop.onNext();
 assert.equal(actor.x,80,'stage two starts inside the compact arena');assert.equal(Game.clearSequence,null);assert.equal(Game.stageIntro.location,'와인 저장고');assert.equal(Game.stageIntro.enemyName,'미츄헨 데슈타프');
 assert.equal(actor.hp,67);assert.equal(actor.lives,2);assert(actor.ownedSubweapons.has('cross'));
 assert.equal(actor.allowZeroHp,false);
 Game.advanceStageIntro(4500);loop(10);loop(50);
 const bossDraw=draws.find(a=>a.length===9&&a[0].width===3216);assert(bossDraw);assert.equal(bossDraw[4],201);assert.equal(bossDraw[6],-201);
 assert(draws.some(a=>a.length===9&&a[7]===1920&&a[8]===720),'cellar background spans the whole map');
 for(const object of Game.Stages.wineCellar.objects)assert(draws.some(a=>a.length===5&&a[1]===object.x&&a[2]===object.y&&a[3]===180&&a[4]===180),'large barrels render independently at their row positions');
 assert.equal(Game.Stages.wineCellar.objects.length,21);
 for(const y of [120,300,480])assert.equal(Game.Stages.wineCellar.objects.filter(object=>object.y===y).length,7);
 loop(80);loop(110);
 actor.x=2000;loop(140);loop(170);assert(actor.x+actor.w<=1920,'stage two clamps the player to its 1920-pixel arena');assert(translations.some(a=>a[0]===-640),'stage two scrolls to its right boundary');
 actor.hp=0;loop(200);loop(230);assert(Game.deathState);assert.equal(actor.lives,1);assert(Game.deathState.canReturnShop);handlers.get('return-shopclick')();assert.equal(actor.hp,67);assert.equal(actor.lives,1);assert.equal(Game.shop.restored.points,2500);assert.equal(Game.shop.restored.restoring,true);assert.equal(typeof Game.shop.onNext,'function');
 console.log('PASS: death and shop rollback, scrolling and cellar transition, discovered/default names, retained player state and placed boss idle.');
});
