window.Game = window.Game || {};
Game.Characters = Game.Characters || {};

Game.Characters.rubania = {
  id: "rubania",
  name: "루바니아",
  spriteRoot: "sprites/rubania",
  spriteScale: 1,
  moves: {
    crouch: true,
    run: true,
    backstep: true,
    slide: true,
    variableJump: true,
    dropKick: true,
    attack: true,
    subweapon: true
  },
  stats: {
    bodyW: 74,
    standH: 170,
    crouchH: 85,
    maxJumps: 1,
    walkSpd: 3.2,
    runSpd: 5.6,
    jumpV: -11,
    jumpCut: 0.4,
    jumpCutBelow: -2,
    gravity: 0.42,
    maxFall: 12,
    backstepSpd: 5.4,
    backstepTime: 22,
    slideSpd: 9.6,
    slideDamage: 3,
    slideTime: 20,
    slideRecoverTime: 14,
    kickFall: 8.5,
    kickDamage: 5,
    kickDiagSpd: 10,
    kickBounceInvuln: 24,
    attackTime: 16,
    whipDamage: 20,
    attackRecoverTime: 16,
    tapWindow: 20,
    maxHp: 100,
    hitRatioM: 0.3,
    hitStun: { S: 14, M: 22 },
    hitKnock: { S: 0.5, M: 3.2 },
    hitFriction: 0.82,
    hitInvuln: 36,
    animIdle: 0.08,
    animWalk: 0.18,
    animRun: 0.28,
    animAir: 0.2,
    maxMp: 100,
    mpRegen: 0.04,
    clockMinMp: 20,
    clockDrain: 1,
    clockDrainInterval: 6,
    knifeCost: 10,
    knifeDamage: 8,
    knifeSpeed: 16,
    knifeLife: 90,
    knifeW: 68,
    knifeH: 22,
    crossCost: 20,
    crossDamage: 6,
    crossTick: 10,
    crossSpeed: 6.5,
    crossOutTime: 64,
    crossMax: 3,
    crossHoverTime: 18,
    crossSpin: 0.3,
    crossSize: 64,
    axeCost: 15,
    axeDamage: 28,
    axeSpeed: 4.68,
    axeV: -26.1,
    axeGravity: 1.0814,
    axeFallGravity: 0.65,
    axeMaxFall: 18,
    axeSpin: 0.2,
    axeW: 44,
    axeH: 64,
    holyCost: 15,
    holySpeed: 7,
    holyV: -3.2,
    holyGravity: 0.42,
    holyMaxFall: 11,
    holyW: 32,
    holyH: 48,
    holySpin: 0.18,
    holyFlameTime: 120,
    holyFlameW: 78,
    holyFlameH: 96,
    holyDamage: 4,
    holyTick: 8
  },
  slideHit: { w: 22, h: 14 },
  kickHit: { w: 74, h: 40, reach: 24 },
  attackHit: {
    stand: { forward: 16, lift: 88, w: 480, h: 36 },
    crouch: { forward: 40, lift: 16, w: 420, h: 64 },
    air: { forward: 16, lift: 90, w: 490, h: 36 }
  },
  anims: {
    idle: { sheet: "idle_sheet.png", frameW: 203, frameH: 203 },
    walk: { sheet: "walk_sheet.png", frameW: 204, frameH: 204 },
    jump: { file: "jump.png" },
    crouch: { file: "crouch2.png" },
    run: { sheet: "run_sheet.png", frameW: 204, frameH: 204 },
    backstep: { sheet: "backstep_sheet.png", frameW: 203, frameH: 203 },
    slide: { file: "Sliding.png" },
    kickVertical: { file: "vertical_drop_kick.png" },
    kickDiagonal: { file: "diagonal_drop_kick.png" },
    attackStand: { sheet: "frontattack.png", frameW: 256, frameH: 256, extra: ["attackStand_fullwhip.png"] },
    attackCrouch: { sheet: "crouchfrontattack_sheet2.png", frameW: 640, frameH: 320, extra: ["attackCrouch_fullwhip2.png"] },
    attackAir: { sheet: "airfrontattack_sheet.png", frameW: 256, frameH: 256, extra: ["attackAir_fullwhip.png"] },
    hit: {
      SF: "SdamageF.png",
      SB: "SdamageB.png",
      MF: "MdamageF.png",
      MB: "MdamageB.png"
    }
  }
};
